import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderMobile from '@/components/header/header-mobile'
import Header from '@/components/header/header'
import ThemeProvider from '@/components/providers/theme-provider'
import Footer from '@/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <HeaderMobile />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
