import { AuthProvider } from '@/contexts/auth-context'
import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, ctx
}: {
  children: React.ReactNode
  ctx?: any
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <AuthProvider ctx={ctx}>
          {children}
        </AuthProvider>
        {/* <Header />
        {children} */}
      </body>
    </html>
  )
}
