import { AuthProvider } from '@/contexts/auth-context'
import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderMobile from '@/components/header/header-mobile'
import Header from '@/components/header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          <HeaderMobile />
          {children}
        </AuthProvider>
        {/* <Header />
        {children} */}
      </body>
    </html>
  )
}
